### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files - in app/config/security.yml, line 19

### ISSUE THREAD

**Issue by Dev-Int** [GLSR/glsr#34]
**[in app/config/security.yml, line 19](https://github.com/GLSR/glsr/blob/2abd301e634d49d393bce5008b1ed816d75e83cf/app/config/security.yml#L19)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/de223fd6-2d6b-4433-a70a-08e09fa68510/analyses/8?status=ignored)_
